### ISSUE TITLE
Support for target devices

### ISSUE THREAD

**Issue by ShoziX** [pschraut/UnityHeapExplorer#15]
Are there any plans of adding the support for the targets devices? It would be really helpful as I love using heap explorer over the unitys one.

**Comment by pschraut** [comment]
That should already work. However, you have to use Unity's Profiler to connect to the target device. When it's connected, you can take a memory captures with Heap Explorer from the connected device.

It's explained at https://github.com/pschraut/UnityHeapExplorer#how-to-capture-a-memory-snapshot
