### ISSUE TITLE
Lost native connections when loading from file

### ISSUE THREAD

**Issue by jojo59516** [pschraut/UnityHeapExplorer#5]
Hi, 
Thank you for bringing us the awesome UnityHeapExplorer!
I found that when I use `Capture and Analyze`, everything is OK. But when I use `Open...` to load snapshot from file, all native objects' references seems to be dropped, without any errors or warnings.

When use `Capture and Analyze`: 
![image](https://user-images.githubusercontent.com/13331846/113846600-39ddf400-97c9-11eb-9dc5-469771162b1f.png)

When use `Open...`:
![image](https://user-images.githubusercontent.com/13331846/113846824-73aefa80-97c9-11eb-818e-06622d9274d9.png)

Is this a known issue? (Btw, my Unity version is 2019.4.5f1.)
Thanks!

**Comment by pschraut** [comment]
Thank you for the bug-report. I didn't know about this issue, but I'm able to reproduce it.

**Comment by pschraut** [comment]
I just pushed a fix. Could you please test if it's fixed for you in Heap Explorer 3.8.0?

Old snapshots don't include the connections, but when you capture a new snapshot, then save and load it, it should restore the connections properly.

Please let me know if it works for you.

**Comment by jojo59516** [comment]
Nice! It works.
Thank you.
